// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using TestSdk.Http;
using TestSdk.Http.Serialization;
using TestSdk.Models;

namespace TestSdk.Services;

public class PetsService : BaseService
{
    internal PetsService(HttpClient httpClient)
        : base(httpClient) { }

    /// <param name="limit">How many items to return at one time (max 100)</param>
    public async Task<List<Pet>> ListPetsAsync(
        long? limit = null,
        CancellationToken cancellationToken = default
    )
    {
        var request = new RequestBuilder(HttpMethod.Get, "pets")
            .SetOptionalQueryParameter("limit", limit)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<List<Pet>>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    public async Task CreatePetsAsync(Pet input, CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "pets")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();
    }

    /// <param name="petId">The id of the pet to retrieve</param>
    public async Task<Pet> ShowPetByIdAsync(
        string petId,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(petId, nameof(petId));

        var request = new RequestBuilder(HttpMethod.Get, "pets/{petId}")
            .SetPathParameter("petId", petId)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<Pet>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
